### PR TITLE
Rename module and update mirrors (gh issue #98).

### PR DESCRIPTION
**Pull request by CFGrote**
Please review changes and merge.

### CODE REVIEW

**Comment by buzmakov** [comment]
@samoylv  Have you look on it. 
For me looks fine, but I don't test it.

**Comment by samoylv** [comment]
Looks fine for me too. Maybe we can merge and test?

**Comment by buzmakov** [comment]
Done

**Comment by buzmakov** [comment]
We defenetly should add test to run prop in our tests.
See #103

**Pull request merged**
