### PR TITLE
Feature/openmp

### PR DESCRIPTION
**Pull request by CFGrote**
Requesting pull to fix eucall-software/WPG issue#2 in eucall-software/WPG upstream.

### CODE REVIEW

**Comment by CFGrote** [comment]
@samoylv , @buzmakov , please review.

**Comment by buzmakov** [comment]
@CFGrote  @samoylv Hi, I have reviewed this change and ready to push it.

@CFGrote arsten I have a question, you change a lot of spaces in Oleg's srwlib.py. Is it necessary to your PEP8 linters ?  
Oleg will change all back in next release of SRW and I need some reasons to try push your changes to root SRW library (to keep one database with Oleg)

**Comment by CFGrote** [comment]
hm, yes, my editor adjusts spaces automatically, whenever I open and
save a file. In this case it probably makes sense to revert.

But do I get this right, srwlib.py is originally in SRW and then copied
(AND COMMITED) to WPG repo?

Carsten

On Tue, Sep 19, 2017 at 02:58:40AM -0700, Alexey Buzmakov wrote:
> @CFGrote  @samoylv Hi, I have reviewed this change and ready to push it.
>
> @CFGrote arsten I have a question, you change a lot of spaces in Oleg's srwlib.py. Is it necessary to your PEP8 linters ?
> Oleg will change all back in next release of SRW and I need some reasons to try push your changes to root SRW library (to keep one database with Oleg)
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/samoylv/WPG/pull/116#issuecomment-330490966

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax:   +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165

**Comment by samoylv** [comment]
the push is fine with me. 
@buzmakov: please confirm that the following is correct: srwlib.py is taken originally from SRW and with a few modifications implemented for WPG compatibility is committed to WPG repo afterwards

**Comment by buzmakov** [comment]
Yes, there are only some small changes to support import srw as library

**Comment by CFGrote** [comment]
thanks.
but would it not be less complicated to copy srwlib.py from srw, patch
it but NOT git add it to WPG? Then we only have to maintain one version
(and a patch) but the file would not exist in two separate repos. just a
suggestion.

carsten

On Tue, Sep 19, 2017 at 02:55:31PM -0700, Alexey Buzmakov wrote:
> Merged #116.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/samoylv/WPG/pull/116#event-1256375988

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax:   +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165

**Pull request merged**
